### ISSUE TITLE
Down arrow goes to the wrong item if the item list changed immediately before

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#290]
For example, say 3rd issue is selected and a refresh adds another issue above the selected issue. Pressing the down arrow will jump to the originally in 5th position instead of the one at 4th position.

**Comment by dariusf** [comment]
I've fixed the problem with an issue itself disappearing. The other problems are harder, due to the lack of control we have over the JavaFX list.

To summarise the issues:

- The model of selection we keep remains correct. Selection moving to wrong items is a visual glitch.
- It's hard to distinguish cases where selection jumps to the top and cases where it moves due to things being added.
- We know when the refresh is completed, but we don't know when the list actually finishes updating. Selecting an item on refresh doesn't work because the list may not actually have reflected the changes.

The alternatives mentioned just now are:

- Intercepting default arrow key behaviour and handling the events ourselves. Quick and easy implementation and almost works, but a major problem with this is that the list doesn't scroll naturally. There doesn't seem to be an easy way to override scrolling behaviour (big class hierarchy, complicated interdependencies, mostly private methods).
- Implementing selection on top of [this](https://github.com/TomasMikula/Flowless) low-level layout widget. More work, but the upsides of this are a greater degree of control, selection and jumping issues going away, ability to lazily scroll through large lists.

**Comment by dariusf** [comment]
Fixed in b985fe9244e97a3eb5ca57f339396b18f07fd513 and d0b6501803b2ade7de5aadf5264fef0f13060bb2.

I found a way to scroll a listview programmatically, which allowed me to implement the first fix. Flowless may be a viable direction for the future but has its share of quirks too.

**Comment by damithc** [comment]
Nice. I'm always a bit wary of third-party libraries, especially immature
ones.

**Comment by damithc** [comment]
The issue is not completely solved. I observed in the following situation:
nth issue is selected. 
1.move to bView and modify that issue.
2. move to HT and press down arrow. selection goes to the next issue (correct).
nth issue disappears due to the changes done a moment ago. This is delayed because refreshing 3. takes  few seconds.
4. wrong issue is selected (selection changes to the wrong issue).

**Comment by dariusf** [comment]
Okay, I'll fix this for the release later.

**Comment by damithc** [comment]
Another situation:
The selected issue disappears from the panel. The next issue is selected automatically. However, that issue is not loaded in bView (i guess that's fine).
I click on the selected issue. It does not load in the bView. I press enter. Still it doesn't load in bView.

Another situation:
The selected issue is loaded in bView. I click on a link in the bView, making it load a different page. I click on the issue again to load the issue page again in bView. But nothing happens.

**Comment by dariusf** [comment]
Both of these seem to have been fixed in V0.9.0. The first was addressed together with the previous one, and the second no longer happens -- it might have been caused by the bug with label-handling, like in #302.
